baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'awesomeverse'

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[module]
    [[module.imports]]
        path = 'github.com/imfing/hextra'