baseURL = 'lynxoo.github.io/awesomeverse/'
languageCode = 'en-us'
title = 'awesomeverse'
enableEmoji = true
enableGitInfo = true

[caches]
[caches.images]
dir = ':cacheDir/images'

[module]
[[module.imports]]
path = 'github.com/imfing/hextra'

[params]
displayUpdatedDate = true
dateFormat = "January 2, 2006"
breadcrumbs = false

[params.search]
enable = true        # 🔥 włącza search
placeholder = "Search the Awesomeverse..."
maxResults = 20

[params.navbar]
displayTitle = true
displayLogo = true
[params.navbar.logo]
path = "/awesomeverse/images/logo.png"
dark = "/awesomeverse/images/logo.png"
link = "/awesomeverse/"
width = 50
height = 50

# ----------------------------------------
# Navbar links
# ----------------------------------------
[menu]

[[menu.main]]
name = "Home"
url = "/docs/"
weight = 1

[[menu.main]]
name = "GitHub"
url = "https://github.com/lynxoo/awesomeverse"
weight = 2

[[menu.main]]
name = "Search"
weight = 4
params = {"type"= "search"}
